import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/Providers";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " text-text bg-background"}>
        <div className="app flex flex-col gap-4 h-screen">
          <Providers>
            <TheHeader />
            <main className="flex-grow">{children}</main>
            <TheFooter />
          </Providers>
        </div>
      </body>
    </html>
  );
}
